# Generated by Django 4.2.1 on 2023-05-26 12:53

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('functional', '0003_functional_city_functional_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='functional',
            options={},
        ),
        migrations.AlterField(
            model_name='functional',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functional.city'),
        ),
        migrations.AlterField(
            model_name='functional',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
