# Generated by Django 4.2.1 on 2023-05-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functional', '0004_mymodel_alter_functional_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
