# Generated by Django 4.2.1 on 2023-05-26 13:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('functional', '0005_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='functional',
            name='countr',
            field=django_countries.fields.CountryField(default='default_value', max_length=2),
        ),
    ]
